### ISSUE TITLE
Layout editor: group borders should also add padding

### ISSUE THREAD

**Issue by miyconst** [Polyjuice/Polyjuice#60]
Border applied to a virtual group looks wrong:
![group-border-bug](https://cloud.githubusercontent.com/assets/6435556/7565498/121808c8-f7f9-11e4-838c-cd5ad44f8a11.png)

**Comment by warpech** [comment]
I think border should not add padding, but rather be applied outside the element rather than inside.

At simplest form - maybe use CSS `outline` instead of `border`?

**Comment by miyconst** [comment]
How to add border to entire container then?
`outline` will go out of screen or workspace bounds.

For single elements border does add padding.
![group-border-bug](https://cloud.githubusercontent.com/assets/6435556/7565955/d4956956-f7fc-11e4-8148-55a256d6ba2a.png)

**Comment by warpech** [comment]
@tomalec, any ideas?

**Comment by tomalec** [comment]
Set `box-sizing: border-box;` for `.juicy-tile` and `.containerBackground` at https://github.com/Juicy/juicy-tile-list/blob/gh-pages/src/juicy-tile-list.html#L34

**Comment by miyconst** [comment]
@tomalec, this does not solve the problem. Here is my css:

```css
.juicy-tile {
	position: absolute;
	box-sizing: border-box;
}

.containerBackground {
	position: absolute;
	box-sizing: border-box;
	z-index: -1;
}
```

And here is the result:
![group-border-bug](https://cloud.githubusercontent.com/assets/6435556/7580509/3148ada2-f87f-11e4-993b-2b960973e2af.png)

I don't want to remove padding from single bordered elements, instead I want to add the same padding to groups.
